export const products = [
  {
    id: 'prod001',
    name: 'Conjunto Infantil Estampado',
    description: 'Conjunto confortável com camiseta estampada e bermuda.',
    price: 89.9,
    images: [
      '/images/prod001-1.jpg',
      '/images/prod001-2.jpg',
      '/images/prod001-3.jpg',
    ],
    sizes: ['2 anos', '4 anos', '6 anos', '8 anos'],
    colors: ['Azul', 'Vermelho', 'Verde'],
    inStock: true,
    category: 'roupas-infantis',
  },
  {
    id: 'prod002',
    name: 'Vestido Floral Infantil',
    description: 'Vestido leve com estampa floral, ideal para o verão.',
    price: 74.5,
    images: ['/images/prod002-1.jpg', '/images/prod002-2.jpg'],
    sizes: ['2 anos', '4 anos', '6 anos', '8 anos', '10 anos'],
    colors: ['Rosa', 'Amarelo', 'Lilás'],
    inStock: true,
    category: 'roupas-infantis',
  },
  {
    id: 'prod003',
    name: 'Camiseta Infantil Super-Herói',
    description: 'Camiseta com estampa de super-herói em algodão macio.',
    price: 39.9,
    images: ['/images/prod003-1.jpg', '/images/prod003-2.jpg'],
    sizes: ['4 anos', '6 anos', '8 anos', '10 anos'],
    colors: ['Preto', 'Azul', 'Cinza'],
    inStock: true,
    category: 'roupas-infantis',
  },
  {
    id: 'prod004',
    name: 'Macacão Bebê Listrado',
    description: 'Macacão de algodão com listras delicadas e botões.',
    price: 59.0,
    images: ['/images/prod004-1.jpg', '/images/prod004-2.jpg'],
    sizes: ['RN', '3 meses', '6 meses', '9 meses'],
    colors: ['Branco', 'Bege', 'Azul bebê'],
    inStock: false,
    category: 'roupas-infantis',
  },
  {
    id: 'prod005',
    name: 'Jaqueta Infantil com Capuz',
    description: 'Jaqueta forrada com capuz removível.',
    price: 129.9,
    images: [
      '/images/prod005-1.jpg',
      '/images/prod005-2.jpg',
      '/images/prod005-3.jpg',
    ],
    sizes: ['4 anos', '6 anos', '8 anos'],
    colors: ['Verde militar', 'Preto'],
    inStock: true,
    category: 'roupas-infantis',
  },
  {
    id: 'prod006',
    name: 'Body Bebê Estampado',
    description: 'Body de algodão com estampa divertida e fecho de botão.',
    price: 29.9,
    images: ['/images/prod006-1.jpg', '/images/prod006-2.jpg'],
    sizes: ['RN', '3 meses', '6 meses'],
    colors: ['Azul claro', 'Amarelo', 'Branco'],
    inStock: true,
    category: 'roupas-infantis',
  },
  {
    id: 'prod007',
    name: 'Calça Jeans Infantil',
    description: 'Calça jeans com elástico ajustável na cintura.',
    price: 69.9,
    images: ['/images/prod007-1.jpg', '/images/prod007-2.jpg'],
    sizes: ['2 anos', '4 anos', '6 anos', '8 anos'],
    colors: ['Jeans escuro', 'Jeans claro'],
    inStock: true,
    category: 'roupas-infantis',
  },
  {
    id: 'prod008',
    name: 'Pijama Infantil Longo',
    description: 'Pijama macio com estampa noturna e punhos ajustáveis.',
    price: 54.9,
    images: ['/images/prod008-1.jpg', '/images/prod008-2.jpg'],
    sizes: ['4 anos', '6 anos', '8 anos', '10 anos'],
    colors: ['Cinza', 'Azul marinho', 'Roxo'],
    inStock: true,
    category: 'roupas-infantis',
  },
  {
    id: 'prod009',
    name: 'Shorts Infantil Básico',
    description: 'Shorts de algodão leve, ideal para dias quentes.',
    price: 34.0,
    images: ['/images/prod009-1.jpg', '/images/prod009-2.jpg'],
    sizes: ['2 anos', '4 anos', '6 anos'],
    colors: ['Vermelho', 'Azul', 'Bege'],
    inStock: true,
    category: 'roupas-infantis',
  },
  {
    id: 'prod010',
    name: 'Camisa Polo Infantil',
    description: 'Camisa polo com gola contrastante e botão frontal.',
    price: 49.9,
    images: [
      '/images/prod010-1.jpg',
      '/images/prod010-2.jpg',
      '/images/prod010-3.jpg',
    ],
    sizes: ['2 anos', '4 anos', '6 anos', '8 anos', '10 anos'],
    colors: ['Branco', 'Verde', 'Azul marinho'],
    inStock: true,
    category: 'roupas-infantis',
  },
]
